# Generated by Django 6.0.1 on 2026-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC (Indice de Masse Corporelle)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.IntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('northwest', 'Nord-Ouest'), ('northeast', 'Nord-Est'), ('southwest', 'Sud-Ouest'), ('southeast', 'Sud-Est')], max_length=20, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoker',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=3, null=True, verbose_name='Fumeur'),
        ),
    ]
