# Generated by Django 6.0.1 on 2026-01-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_web', '0002_profile_age_profile_bmi_profile_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('conseiller', 'Conseiller'), ('admin', 'Administrateur')], default='user', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI (Body Mass Index)'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date et heure')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_conseiller', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_time'],
            },
        ),
    ]
