# Generated by Django 6.0.1 on 2026-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_web', '0008_profile_height_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_moved', 'Appointment Moved'), ('appointment_request', 'Appointment Request'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected')], max_length=30, verbose_name='Type'),
        ),
    ]
