from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    HomeView,
    SignupView,
    LogoutView,
    ProfileView,
    EditProfileView,
    PredictView,
    ConseillersListView,
    ConseillerAvailabilityView,
    CreateAppointmentView,
    MyAppointmentsView,
    AppointmentDetailView,
    CancelAppointmentView,
    RescheduleAppointmentView,
    ConseillerDashboardView,
    ConseillerPredictView,
    ConseillerCalendarView,
    ConseillerCalendarCreateAppointmentView,
    AddUnavailabilityView,
    DeleteUnavailabilityView,
    ConseillerClientsListView,
    ConseillerClientDetailView,
    ConseillerCreateAppointmentView,
    DeletePredictionView,
    RemoveClientView,
    NotificationListView,
    MarkNotificationReadView,
    MarkAllNotificationsReadView,
    AcceptAppointmentView,
    RejectAppointmentView,
    AdminDashboardView,
    AdminUserManagementView,
    AdminChangeUserRoleView,
    AdminToggleUserStatusView,
    AdminDeleteUserView,
    PricingConfigurationView,
)

app_name = 'insurance_web'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='authentification/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('predict/', PredictView.as_view(), name='predict'),
    path('conseillers/', ConseillersListView.as_view(), name='conseillers_list'),
    path('conseiller/<int:conseiller_id>/availability/', ConseillerAvailabilityView.as_view(), name='conseiller_availability'),
    path('conseiller/<int:conseiller_id>/book/', CreateAppointmentView.as_view(), name='create_appointment'),
    path('appointments/', MyAppointmentsView.as_view(), name='my_appointments'),
    path('appointments/<int:appointment_id>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointments/<int:appointment_id>/cancel/', CancelAppointmentView.as_view(), name='cancel_appointment'),
    path('appointments/<int:appointment_id>/reschedule/', RescheduleAppointmentView.as_view(), name='reschedule_appointment'),
    
    path('conseiller/', ConseillerDashboardView.as_view(), name='conseiller_dashboard'),
    path('conseiller/predict/', ConseillerPredictView.as_view(), name='conseiller_predict'),
    path('conseiller/predict/<int:client_id>/', ConseillerPredictView.as_view(), name='conseiller_predict_client'),
    path('conseiller/calendar/', ConseillerCalendarView.as_view(), name='conseiller_calendar'),
    path('conseiller/calendar/create/', ConseillerCalendarCreateAppointmentView.as_view(), name='conseiller_calendar_create'),
    path('conseiller/calendar/unavailability/add/', AddUnavailabilityView.as_view(), name='conseiller_add_unavailability'),
    path('conseiller/calendar/unavailability/<int:unavailability_id>/delete/', DeleteUnavailabilityView.as_view(), name='conseiller_delete_unavailability'),
    path('conseiller/clients/', ConseillerClientsListView.as_view(), name='conseiller_clients'),
    path('conseiller/clients/<int:client_id>/', ConseillerClientDetailView.as_view(), name='conseiller_client_detail'),
    path('conseiller/clients/<int:client_id>/book-new/', ConseillerCreateAppointmentView.as_view(), name='conseiller_create_appointment'),
    path('conseiller/predictions/<int:prediction_id>/delete/', DeletePredictionView.as_view(), name='delete_prediction'),
    path('conseiller/clients/<int:client_id>/remove/', RemoveClientView.as_view(), name='remove_client'),
    path('conseiller/appointments/<int:appointment_id>/accept/', AcceptAppointmentView.as_view(), name='accept_appointment'),
    path('conseiller/appointments/<int:appointment_id>/reject/', RejectAppointmentView.as_view(), name='reject_appointment'),
    
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:notification_id>/read/', MarkNotificationReadView.as_view(), name='mark_notification_read'),
    path('notifications/read-all/', MarkAllNotificationsReadView.as_view(), name='mark_all_notifications_read'),
    
    path('management/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('management/users/', AdminUserManagementView.as_view(), name='admin_user_management'),
    path('management/users/<int:user_id>/change-role/', AdminChangeUserRoleView.as_view(), name='admin_change_user_role'),
    path('management/users/<int:user_id>/toggle-status/', AdminToggleUserStatusView.as_view(), name='admin_toggle_user_status'),
    path('management/users/<int:user_id>/delete/', AdminDeleteUserView.as_view(), name='admin_delete_user'),
    path('management/pricing/', PricingConfigurationView.as_view(), name='pricing_configuration'),
]
